version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6820
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6820:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://192.168.236.81:6701
      CallBackUrl: http://localhost:6821
      ASPNETCORE_ENRIONMENT : Development
    ports:
      - "6821:80"
    container_name: eventswebmvc
    networks:
      - frontend
    depends_on:
      - catalog

  tokenserver:
    image: jewels/tokenapi
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile    
    environment: 
      Mvcclient: http://localhost:6821
    ports:
      - "6701:80"
    container_name: tokenserviceapi
    networks: 
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1449:1433"
    container_name: eventssqlserver
    networks:
      - backend